contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/zwave-js/zwave-js-ui/discussions/new
    about: Share ideas for new features
  - name: â“ Question
    url: https://github.com/zwave-js/zwave-js-ui/discussions/new
    about: General questions