version: "3.7"
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
    # - TZ=America/Los_Angeles  # uncomment and edit to match you timezone if you want logs time and dates to match your timezone instead of UTC.
    networks:
      - zwave
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - ./store:/usr/src/app/store
      - zwave-config:/usr/src/app/node_modules/@zwave-js/config
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for zwave-js websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
