version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - zwave
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - '8091:8091'  # port for web interface
      - '3000:3000'  # port for zwave-js websocket server
networks:
  zwave:
# volumes:
#   zwavejs2mqtt:
#     name: zwavejs2mqtt

