version: "3.4"

services:

    nginx:
      image: nginx:alpine
      container_name: "nginx"
      volumes:
        - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./etc/nginx.conf:/etc/nginx/nginx.conf
        - ./etc/proxy.conf:/etc/nginx/proxy.conf
        - ./etc/nginx.crt:/etc/nginx/nginx.crt
        - ./etc/nginx.key:/etc/nginx/nginx.key
      restart: always
      network_mode: "host"


