name: Docker Test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: [linux/amd64, linux/arm64, linux/arm/v7]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/setup-qemu-action@v3

      - uses: actions/github-script@v6
        id: ref-sanitized
        with:
          script: |
            const ref = context.ref
            return ref.replace(/^refs\/heads\/|-/, '')

      - name: Create Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: zwavejs/zwavejs2mqtt,zwavejs/zwave-js-ui,ghcr.io/zwave-js/zwave-js-ui
          tags: |
            test
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.vendor=zwave-js
            org.opencontainers.image.documentation=https://zwave-js.github.io/zwave-js-ui/#/
            org.opencontainers.image.authors=Daniel Lando <daniel.sorridi@gmail.com>
            org.opencontainers.image.url=https://zwave-js.github.io/zwave-js-ui/#/
            maintainer=robertsLando

      - name: Buildx build
        uses: docker/build-push-action@v5
        timeout-minutes: 120
        with:
          platforms: ${{ matrix.platform }}
          file: docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
