# This is a basic workflow to help you get started with Actions

name: Update Zwave-JS

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'latest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          cache: 'yarn'

      # Runs a single command using the runners shell
      - name: Update zwave-js
        run: |
          yarn add zwave-js@${{github.event.inputs.version}}
      - name: Check for changes
        id: check
        run: |
          git diff --name-only || true
          if ! git diff --quiet ; then
            echo "has changes"
            git diff > fix.patch
            echo "::set-output name=changed::true"
            VERSION=$(yarn info --silent zwave-js version)
            echo "::set-output name=version::$VERSION"
          else
            echo "unchanged"
            echo "::set-output name=changed::false"
          fi
      - name: Create Pull Request
        if: ${{ steps.check.outputs.changed == 'true' }}
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: "feat: bump zwave-js@${{ steps.check.outputs.version }}"
          committer: Z-Wave JS Bot <bot@zwave-js.io>
          author: Z-Wave JS Bot <bot@zwave-js.io>
          signoff: false
          branch: "zwave-js@${{ steps.check.outputs.version }}"
          delete-branch: true
          title: "feat: bump zwave-js@${{ steps.check.outputs.version }}"
          body: |
            Update zwave-js to version ${{ steps.check.outputs.version }}
          labels: |
            dependencies
            zwave-js
          base: master
          draft: false

      - name: Check outputs
        if: ${{ steps.check.outputs.changed == 'true' }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"